export enum AppEvent {
  INIT = 'INIT',
  SEARCH = 'SEARCH',
  CLONE = 'CLONE',
  PULL = 'PULL',
  OPEN_DIR = 'OPEN_DIR',
  OPEN_REPO = 'OPEN_REPO',
  OPEN_FILE = 'OPEN_FILE',
  UP$ = "UP$",
  DOWN$ = "DOWN$",
  DETAIL_REPO = "DETAIL_REPO",
  LOCALSTACK_INIT="LOCALSTACK_INIT",
  LOCALSTACK_NAV="LOCALSTACK_NAV"
}